config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :arquivos
  root :to => "apresentacoes#index"
  resources :minha_paginas

  resources :desaparecidos
  resources :apresentacoes do
    collection do
      get 'colaboradores'
      get 'patrocinadores'
      get 'sobre'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/arquivo.rb
class Arquivo < ApplicationRecord
  belongs_to :table, polymorphic: true
end

app/models/desaparecido.rb
class Desaparecido < ApplicationRecord
  has_many :arquivos, as: 'table'
  enum sexo: {masculino: 0, feminino: 1}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/apresentacoes_controller.rb
class ApresentacoesController < ApplicationController
  layout 'home'
  def index

  end
  def colaboradores

  end
end

app/controllers/desaparecidos_controller.rb
class DesaparecidosController < ApplicationController
  before_action :set_desaparecido, only: [:show, :edit, :update, :destroy]
  layout 'external'
  # GET /usuarios
  # GET /usuarios.json
  def index
    @desaparecido = Desaparecido.all
  end


  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    render layout:'application'
    @desaparecido = Desaparecido.new
  end

  # GET /usuarios/1/edit
  def edit
    @desaparecido = autenticacao
    render layout:'application'
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @desaparecido = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save!
        format.html { redirect_to @usuario, notice: 'Usuário gravado com sucesso.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_usuario
    @usuario = autenticacao
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def usuario_params
    params.require(:usuario).permit(:nome, :senha, :telefone, :email, :endereco)
  end
end

app/controllers/minha_paginas_controller.rb
class MinhaPaginasController < ApplicationController
  before_action :set_minha_pagina, only: [:autenticacao, :show, :edit, :update, :destroy]
  def autenticacao
    autenticacao
  end

  # GET /minha_paginas
  # GET /minha_paginas.json
  def index
  end

  # GET /minha_paginas/1
  # GET /minha_paginas/1.json
  def show
  end

  # GET /minha_paginas/new
  def new
    @minha_pagina = MinhaPagina.new
  end

  # GET /minha_paginas/1/edit
  def edit
    @usuario = autenticacao
  end

  # POST /minha_paginas
  # POST /minha_paginas.json
  def create
    @minha_pagina = MinhaPagina.new(minha_pagina_params)

    respond_to do |format|
      if @minha_pagina.save
        format.html { redirect_to @minha_pagina, notice: 'Minha pagina was successfully created.' }
        format.json { render :show, status: :created, location: @minha_pagina }
      else
        format.html { render :new }
        format.json { render json: @minha_pagina.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /minha_paginas/1
  # PATCH/PUT /minha_paginas/1.json
  def update
    respond_to do |format|
      if @minha_pagina.update(minha_pagina_params)
        format.html { redirect_to @minha_pagina, notice: 'Minha pagina was successfully updated.' }
        format.json { render :show, status: :ok, location: @minha_pagina }
      else
        format.html { render :edit }
        format.json { render json: @minha_pagina.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /minha_paginas/1
  # DELETE /minha_paginas/1.json
  def destroy
    @minha_pagina.destroy
    respond_to do |format|
      format.html { redirect_to minha_paginas_url, notice: 'Minha pagina was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_minha_pagina
      @minha_pagina = MinhaPagina.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def minha_pagina_params
      params.fetch(:minha_pagina, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apresentacoes_helper.rb
module ApresentacoesHelper
end

app/helpers/arquivos_helper.rb
module ArquivosHelper
end

app/helpers/desaparecidos_helper.rb
module DesaparecidosHelper
end

app/helpers/minha_paginas_helper.rb
module MinhaPaginasHelper
end

app/views/apresentacoes/colaboradores.html.erb
<div class="ui inverted vertical masthead center aligned segment">

  <div class="ui container">
    <div class="ui large secondary inverted pointing menu">
      <a class="toc item">
        <i class="sidebar icon"></i>
      </a>
      <%= link_to 'Sobre', sobre_apresentacoes_path, class: 'item' %>
      <%= link_to 'Apresentação', apresentacoes_path, class: 'item' %>
      <%= link_to 'Colaboradores', colaboradores_apresentacoes_path, class: 'item active' %>
      <%= link_to 'Patrocinadores', patrocinadores_apresentacoes_path, class: 'item'  %>
      <%= link_to 'Buscar', desaparecidos_path, class: 'item'  %>
    </div>
  </div>

  <div class="ui text container">
    <h1 class="ui inverted header">
      Desaparecidos
    </h1>
    <h2>Conheça as pessoas que colaboraram para esse projeto.</h2>
  </div>

</div>

<div class="ui vertical stripe segment">
  <div class="ui middle aligned stackable grid container">
    <div class="row">
      <div class="eight wide column">
        <h3 class="ui header">We Help Companies and Companions</h3>
        <p>We can give your company superpowers to do things that they never thought possible. Let us delight your customers and empower your needs...through pure data analytics.</p>
        <h3 class="ui header">We Make Bananas That Can Dance</h3>
        <p>Yes that's right, you thought it was the stuff of dreams, but even bananas can be bioengineered.</p>
      </div>
      <div class="six wide right floated column">
        <img src="https://semantic-ui.com/examples/assets/images/wireframe/white-image.png" class="ui large bordered rounded image">
      </div>
    </div>
    <div class="row">
      <div class="center aligned column">
        <a class="ui huge button">Check Them Out</a>
      </div>
    </div>
  </div>
</div>


<div class="ui vertical stripe quote segment">
  <div class="ui equal width stackable internally celled grid">
    <div class="center aligned row">
      <div class="column">
        <h3>"What a Company"</h3>
        <p>That is what they all say about us</p>
      </div>
      <div class="column">
        <h3>"I shouldn't have gone with their competitor."</h3>
        <p>
          <img src="https://semantic-ui.com/examples/assets/images/avatar/nan.jpg" class="ui avatar image"> <b>Nan</b> Chief Fun Officer Acme Toys
        </p>
      </div>
    </div>
  </div>
</div>

<div class="ui vertical stripe segment">
  <div class="ui text container">
    <h3 class="ui header">Breaking The Grid, Grabs Your Attention</h3>
    <p>Instead of focusing on content creation and hard work, we have learned how to master the art of doing nothing by providing massive amounts of whitespace and generic content that can seem massive, monolithic and worth your attention.</p>
    <a class="ui large button">Read More</a>
    <h4 class="ui horizontal header divider">
      <a href="#">Case Studies</a>
    </h4>
    <h3 class="ui header">Did We Tell You About Our Bananas?</h3>
    <p>Yes I know you probably disregarded the earlier boasts as non-sequitur filler content, but its really true. It took years of gene splicing and combinatory DNA research, but our bananas can really dance.</p>
    <a class="ui large button">I'm Still Quite Interested</a>
  </div>
</div>

app/views/apresentacoes/index.html.erb
<div class="ui inverted vertical masthead center aligned segment">

  <div class="ui container">
    <div class="ui large secondary inverted pointing menu">
      <a class="toc item">
        <i class="sidebar icon"></i>
      </a>

      <%= link_to 'Sobre', sobre_apresentacoes_path, class: 'item' %>
      <%= link_to 'Apresentação', apresentacoes_path, class: 'item active' %>
      <%= link_to 'Colaboradores', colaboradores_apresentacoes_path, class: 'item' %>
      <%= link_to 'Patrocinadores', patrocinadores_apresentacoes_path, class: 'item'  %>
      <%= link_to 'Buscar', desaparecidos_path, class: 'item'  %>
    </div>
  </div>

  <div class="ui text container">
    <h1 class="ui inverted header">
      Desaparecidos
    </h1>
    <h2>Conheça as pessoas que colaboraram para esse projeto.</h2>
    <%= link_to 'Logar', user_session_path, class: 'ui huge primary button'  %>
    <%= link_to 'Cadastrar', new_user_registration_path, class: 'ui huge primary button'  %>
  </div>

</div>

<div class="ui vertical stripe segment">
  <div class="ui middle aligned stackable grid container">
    <div class="row">
      <div class="eight wide column">
        <h3 class="ui header">We Help Companies and Companions</h3>
        <p>We can give your company superpowers to do things that they never thought possible. Let us delight your customers and empower your needs...through pure data analytics.</p>
        <h3 class="ui header">We Make Bananas That Can Dance</h3>
        <p>Yes that's right, you thought it was the stuff of dreams, but even bananas can be bioengineered.</p>
      </div>
      <div class="six wide right floated column">
        <img src="https://semantic-ui.com/examples/assets/images/wireframe/white-image.png" class="ui large bordered rounded image">
      </div>
    </div>
    <div class="row">
      <div class="center aligned column">
        <a class="ui huge button">Check Them Out</a>
      </div>
    </div>
  </div>
</div>


<div class="ui vertical stripe quote segment">
  <div class="ui equal width stackable internally celled grid">
    <div class="center aligned row">
      <div class="column">
        <h3>"What a Company"</h3>
        <p>That is what they all say about us</p>
      </div>
      <div class="column">
        <h3>"I shouldn't have gone with their competitor."</h3>
        <p>
          <img src="https://semantic-ui.com/examples/assets/images/avatar/nan.jpg" class="ui avatar image"> <b>Nan</b> Chief Fun Officer Acme Toys
        </p>
      </div>
    </div>
  </div>
</div>

<div class="ui vertical stripe segment">
  <div class="ui text container">
    <h3 class="ui header">Breaking The Grid, Grabs Your Attention</h3>
    <p>Instead of focusing on content creation and hard work, we have learned how to master the art of doing nothing by providing massive amounts of whitespace and generic content that can seem massive, monolithic and worth your attention.</p>
    <a class="ui large button">Read More</a>
    <h4 class="ui horizontal header divider">
      <a href="#">Case Studies</a>
    </h4>
    <h3 class="ui header">Did We Tell You About Our Bananas?</h3>
    <p>Yes I know you probably disregarded the earlier boasts as non-sequitur filler content, but its really true. It took years of gene splicing and combinatory DNA research, but our bananas can really dance.</p>
    <a class="ui large button">I'm Still Quite Interested</a>
  </div>
</div>

app/views/apresentacoes/patrocinadores.html.erb
<div class="ui inverted vertical masthead center aligned segment">

  <div class="ui container">
    <div class="ui large secondary inverted pointing menu">
      <a class="toc item">
        <i class="sidebar icon"></i>
      </a>

      <%= link_to 'Sobre', sobre_apresentacoes_path, class: 'item' %>
      <%= link_to 'Apresentação', apresentacoes_path, class: 'item' %>
      <%= link_to 'Colaboradores', colaboradores_apresentacoes_path, class: 'item' %>
      <%= link_to 'Patrocinadores', patrocinadores_apresentacoes_path, class: 'item active' %>
      <%= link_to 'Buscar', desaparecidos_path, class: 'item'  %>
    </div>
  </div>

  <div class="ui text container">
    <h1 class="ui inverted header">
      Desaparecidos
    </h1>
    <h2>Conheça nossos patrocinadores.</h2>
  </div>

</div>

<div class="ui vertical stripe segment">
  <div class="ui middle aligned stackable grid container">
    <div class="row">
      <div class="eight wide column">
        <h3 class="ui header">We Help Companies and Companions</h3>
        <p>We can give your company superpowers to do things that they never thought possible. Let us delight your customers and empower your needs...through pure data analytics.</p>
        <h3 class="ui header">We Make Bananas That Can Dance</h3>
        <p>Yes that's right, you thought it was the stuff of dreams, but even bananas can be bioengineered.</p>
      </div>
      <div class="six wide right floated column">
        <img src="https://semantic-ui.com/examples/assets/images/wireframe/white-image.png" class="ui large bordered rounded image">
      </div>
    </div>
    <div class="row">
      <div class="center aligned column">
        <a class="ui huge button">Check Them Out</a>
      </div>
    </div>
  </div>
</div>


<div class="ui vertical stripe quote segment">
  <div class="ui equal width stackable internally celled grid">
    <div class="center aligned row">
      <div class="column">
        <h3>"What a Company"</h3>
        <p>That is what they all say about us</p>
      </div>
      <div class="column">
        <h3>"I shouldn't have gone with their competitor."</h3>
        <p>
          <img src="https://semantic-ui.com/examples/assets/images/avatar/nan.jpg" class="ui avatar image"> <b>Nan</b> Chief Fun Officer Acme Toys
        </p>
      </div>
    </div>
  </div>
</div>

<div class="ui vertical stripe segment">
  <div class="ui text container">
    <h3 class="ui header">Breaking The Grid, Grabs Your Attention</h3>
    <p>Instead of focusing on content creation and hard work, we have learned how to master the art of doing nothing by providing massive amounts of whitespace and generic content that can seem massive, monolithic and worth your attention.</p>
    <a class="ui large button">Read More</a>
    <h4 class="ui horizontal header divider">
      <a href="#">Case Studies</a>
    </h4>
    <h3 class="ui header">Did We Tell You About Our Bananas?</h3>
    <p>Yes I know you probably disregarded the earlier boasts as non-sequitur filler content, but its really true. It took years of gene splicing and combinatory DNA research, but our bananas can really dance.</p>
    <a class="ui large button">I'm Still Quite Interested</a>
  </div>
</div>

app/views/apresentacoes/sobre.html.erb
<div class="ui inverted vertical masthead center aligned segment">

  <div class="ui container">
    <div class="ui large secondary inverted pointing menu">
      <a class="toc item">
        <i class="sidebar icon"></i>
      </a>


      <%= link_to 'Sobre', sobre_apresentacoes_path, class: 'item active' %>
      <%= link_to 'Apresentação', apresentacoes_path, class: 'item' %>
      <%= link_to 'Colaboradores', colaboradores_apresentacoes_path, class: 'item' %>
      <%= link_to 'Patrocinadores', patrocinadores_apresentacoes_path, class: 'item'  %>
      <%= link_to 'Buscar', desaparecidos_path, class: 'item'  %>
    </div>
  </div>

  <div class="ui text container">
    <h1 class="ui inverted header">
      Desaparecidos
    </h1>
    <h2>Conheça sobre esse projeto.</h2>
  </div>

</div>

<div class="ui vertical stripe segment">
  <div class="ui middle aligned stackable grid container">
    <div class="row">
      <div class="eight wide column">
        <h3 class="ui header">We Help Companies and Companions</h3>
        <p>We can give your company superpowers to do things that they never thought possible. Let us delight your customers and empower your needs...through pure data analytics.</p>
        <h3 class="ui header">We Make Bananas That Can Dance</h3>
        <p>Yes that's right, you thought it was the stuff of dreams, but even bananas can be bioengineered.</p>
      </div>
      <div class="six wide right floated column">
        <img src="https://semantic-ui.com/examples/assets/images/wireframe/white-image.png" class="ui large bordered rounded image">
      </div>
    </div>
    <div class="row">
      <div class="center aligned column">
        <a class="ui huge button">Check Them Out</a>
      </div>
    </div>
  </div>
</div>


<div class="ui vertical stripe quote segment">
  <div class="ui equal width stackable internally celled grid">
    <div class="center aligned row">
      <div class="column">
        <h3>"What a Company"</h3>
        <p>That is what they all say about us</p>
      </div>
      <div class="column">
        <h3>"I shouldn't have gone with their competitor."</h3>
        <p>
          <img src="https://semantic-ui.com/examples/assets/images/avatar/nan.jpg" class="ui avatar image"> <b>Nan</b> Chief Fun Officer Acme Toys
        </p>
      </div>
    </div>
  </div>
</div>

<div class="ui vertical stripe segment">
  <div class="ui text container">
    <h3 class="ui header">Breaking The Grid, Grabs Your Attention</h3>
    <p>Instead of focusing on content creation and hard work, we have learned how to master the art of doing nothing by providing massive amounts of whitespace and generic content that can seem massive, monolithic and worth your attention.</p>
    <a class="ui large button">Read More</a>
    <h4 class="ui horizontal header divider">
      <a href="#">Case Studies</a>
    </h4>
    <h3 class="ui header">Did We Tell You About Our Bananas?</h3>
    <p>Yes I know you probably disregarded the earlier boasts as non-sequitur filler content, but its really true. It took years of gene splicing and combinatory DNA research, but our bananas can really dance.</p>
    <a class="ui large button">I'm Still Quite Interested</a>
  </div>
</div>

app/views/desaparecidas/_form.html.erb
<%= form_with(model: desaparecida, local: true, class: 'ui form') do |form| %>
  <% if desaparecida.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(desaparecida.errors.count, "error") %> prohibited this desaparecida from being saved:</h2>

      <ul>
      <% desaparecida.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="ui divider"></div>
  <div class="field">
    <%= form.label :usuario_id %>
    <%= form.text_field :usuario_id %>
  </div>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :idade %>
    <%= form.number_field :idade %>
  </div>

  <div class="field">
    <%= form.label :sexo %>
    <%= form.number_field :sexo %>
  </div>

  <div class="field">
    <%= form.label :data_nascimento %>
    <%= form.datetime_select :data_nascimento %>
  </div>

  <div class="field">
    <%= form.label :mae %>
    <%= form.text_field :mae %>
  </div>

  <div class="field">
    <%= form.label :pai %>
    <%= form.text_field :pai %>
  </div>

  <div class="ui divider"></div>
  <div class="actions text-left">
    <%= link_to testes_path, class: 'ui basic button' do%>
        <i class='chevron left icon'></i> VOLTAR
     <% end %>
    <%= form.submit :Gravar, class: 'ui primary button' do %>
     <i class='save icon'></i> GRAVAR
    <%end%>
  </div>
<% end %>

app/views/desaparecidos/_form.html.erb
<%= form_with(model: desaparecido, local: true, class: 'ui form') do |form| %>

  <h2 class="ui dividing header">Fotos<a class="anchor" id="variations"></a></h2>



  <div class="field">
    <%= form.label :imagem %>
    <%= form.file_field :imagem %>
  </div>

  <h2 class="ui dividing header">Dados<a class="anchor" id="variations"></a></h2>


  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>



  <div class="field">
    <%= form.label :sexo %>
    <%= form.select :sexo, Desaparecido.sexos.keys, {}, class: 'user-roles-select' %>
  </div>

  <div class="field">
    <%= form.label :data_nascimento %>
    <%= form.text_field :data_nascimento, type: 'date' %>
  </div>

  <div class="field">
    <%= form.label :mae %>
    <%= form.text_field :mae %>
  </div>

  <div class="field">
    <%= form.label :pai %>
    <%= form.text_field :pai %>
  </div>

  <a class="anchor" id="variations"></a>


  <h2 class="ui dividing header"></h2>
  <div class="actions text-left">

    <%= form.button :Gravar, type: 'submit', class: 'ui primary button right floated labeled icon' do %>
      <i class='save icon'></i> GRAVAR
    <%end%>
  </div>
  <br>
  <br>




<% end %>

app/views/desaparecidos/edit.html.erb
<h1>Editar Desaparecido</h1>

<%= render 'form', desaparecido: @desaparecido %>

<%= link_to 'Visualizar', @desaparecido %> |
<%= link_to 'Voltar', desaparecidos_path %>

app/views/desaparecidos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Desaparecidos</h1>

<p id="notice"><%= notice %></p>

<div class="ui grid">



  <div class="four wide computer nine wide tablet six wide mobile column">
    <div class="ui card">
      <div class="image">
        <img src="https://semantic-ui.com/images/avatar2/large/kristy.png">
      </div>
      <div class="content">
        <a class="header">Kristy</a>
        <div class="meta">
          <span class="date">Joined in 2013</span>
        </div>
        <div class="description">
          Kristy is an art director living in New York.
        </div>
      </div>
      <div class="extra content">
        <a>
          <i class="user icon"></i>
          22 Friends
        </a>
      </div>
    </div>

  </div>
  <div class="twelve wide column">
    <div class="row">
      <div class="column">
        <div class="ui message">
          <h1 class="ui header">Hello, world!</h1>
          <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
          <a class="ui blue button">Learn more &raquo;</a>
        </div>
      </div>
    </div>
  </div>
</div>

<p id="notice"><%= notice %></p>

<div class="ui grid">



  <div class="four wide computer nine wide tablet six wide mobile column">
    <div class="ui card">
      <div class="image">
        <img src="https://semantic-ui.com/images/avatar2/large/kristy.png">
      </div>
      <div class="content">
        <a class="header">Kristy</a>
        <div class="meta">
          <span class="date">Joined in 2013</span>
        </div>
        <div class="description">
          Kristy is an art director living in New York.
        </div>
      </div>
      <div class="extra content">
        <a>
          <i class="user icon"></i>
          22 Friends
        </a>
      </div>
    </div>

  </div>
  <div class="twelve wide column">
    <div class="row">
      <div class="column">
        <div class="ui message">
          <h1 class="ui header">Hello, world!</h1>
          <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
          <a class="ui blue button">Learn more &raquo;</a>
        </div>
      </div>
    </div>
  </div>
</div>
<%= link_to 'Novo Desaparecido', new_desaparecido_path %>

app/views/desaparecidos/new.html.erb
<div class="ui borderless main menu">
  <%= link_to 'Perfil', edit_usuarios_path, class: 'item' %>
  <%= link_to 'Desaparecidos', new_desaparecido_path, class: 'item' %>
</div>

<div class="ui large form">
  <div class="ui segment">
    <%= render 'form', desaparecido: @desaparecido %>
  </div>
</div>

app/views/desaparecidos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Usuario:</strong>
  <%= @desaparecido.usuario %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @desaparecido.nome %>
</p>

<p>
  <strong>Idade:</strong>
  <%= @desaparecido.idade %>
</p>

<p>
  <strong>Sexo:</strong>
  <%= @desaparecido.sexo %>
</p>

<p>
  <strong>Data nascimento:</strong>
  <%= @desaparecido.data_nascimento %>
</p>

<p>
  <strong>Mae:</strong>
  <%= @desaparecido.mae %>
</p>

<p>
  <strong>Pai:</strong>
  <%= @desaparecido.pai %>
</p>

<%= link_to 'Editar', edit_desaparecido_path(@desaparecido) %> |
<%= link_to 'Voltar', desaparecidos_path %>

app/views/layouts/external.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Desaparecidos</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.3.3/semantic.min.css" >
  <%= stylesheet_link_tag 'application', media: 'all' %>

</head>

<body>
<div class="ui fixed inverted menu">
  <div class="ui container">
    <a href="/apresentacoes" class="header item">
      <img class="logo" src="https://semantic-ui.com/examples/assets/images/logo.png">
      Desaparecidos
    </a>
    <a href="/apresentacoes" class="item">Home</a>
    <a href="/usuarios/new" class="item">Cadastrar</a>
    <a href="/usuarios/login" class="item">Login</a>
    <a href="/desaparecidos" class="item">Buscar</a>
  </div>
</div>
<div class="ui main container">
  <%= yield %>
</div>
</body>

<script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.3.3/semantic.min.js" crossorigin="anonymous"></script>
<%= javascript_include_tag 'application' %>

</html>

app/views/minha_paginas/_form.html.erb
<%= form_with(model: minha_pagina, local: true) do |form| %>
  <% if minha_pagina.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(minha_pagina.errors.count, "error") %> prohibited this minha_pagina from being saved:</h2>

      <ul>
      <% minha_pagina.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit :Gravar, class: 'btn btn-success' %>
  </div>
<% end %>

app/views/minha_paginas/edit.html.erb
<h1>Editar Minha Pagina</h1>

<%= render 'form', minha_pagina: @minha_pagina %>

<%= link_to 'Visualizar', @minha_pagina %> |
<%= link_to 'Voltar', minha_paginas_path %>

app/views/minha_paginas/new.html.erb
<h1>Novo Minha Pagina</h1>

<%= render 'form', minha_pagina: @minha_pagina %>

<%= link_to 'Voltar', minha_paginas_path %>

app/views/minha_paginas/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Editar', edit_minha_pagina_path(@minha_pagina) %> |
<%= link_to 'Voltar', minha_paginas_path %>